481 display linter errors in terminal
jackstenglein/chess-dojo-scheduler pull request #548
Opened 2024-06-05 22:40 UTC by chao-mu

2024-06-06 14:03 UTC, jackstenglein requested changes

2024-06-06 17:27 UTC, chao-mu commented on frontend/cypress/support/e2e.ts
> +// By importing this here, our custom commands defined in commands.ts
Refers to the same as "this", which is the package.

2024-06-06 17:33 UTC, chao-mu commented on frontend/cypress/tsconfig.json
> +        "strict": true
Looks like it meant have been a merge issue on my end. Thanks!

2024-06-08 04:00 UTC, jackstenglein approved these changes

2024-06-08 05:36 UTC, merged