feat(Roundrobin): Register API integration
jackstenglein/chess-dojo-scheduler pull request #908
Opened 2024-11-17 01:55 UTC by jalpp

2024-11-18 22:06 UTC, jackstenglein requested changes
Please keep it DRY (don't repeat yourself). Research how to share classes between different Lambda handlers. The way it's currently written will be very hard to maintain. What if there's a bug and you need to make a change to `getTournamentCrosstable`? Do you want to update it in one place or three? What if someone else who doesn't know as much about this is updating the code and doesn't know there are 3 copies? Then they find one copy and update just that one, and the code is out of sync between the 3 copies.

2024-11-18 22:06 UTC, jackstenglein commented on backend/roundrobin/RoundRobinRegisterApi/README.md
> +- deploy RoundRobinRegisterAPI-1.0-SNAPSHOT.jar to lambda
Can you check how to use Java with serverless? I'd greatly prefer to not have manual steps in our deployment process

2024-11-18 22:11 UTC, jalpp commented on backend/roundrobin/RoundRobinGameApi/src/main/java/Handler/Platform.java
> +                return "Lichessname";
thats the player name for that platform it shouldn't be toString() tbh but yea

2024-11-18 22:13 UTC, jalpp commented on backend/roundrobin/RoundRobinGameApi/src/main/java/Handler/App.java
> +     * The Connection string.
ok they were auto-generated I was going to add after you reviewed

2024-11-18 22:13 UTC, jalpp commented on backend/roundrobin/RoundRobinGameApi/src/main/java/Handler/App.java
> +    String connectionString = System.getenv("CONNECTION_STRING");
ok

2024-11-18 22:15 UTC, jalpp commented on backend/roundrobin/RoundRobinGameApi/src/main/java/Handler/GameState.java
> +    PLAYER_ONE_WON,
yea I initially mapped player 1 to white and player 2 to black and thats why I kept it that way, that was alias so I can write the code other way around, but now I think of it it is confusing. I will just make it White_won Black_won and draw.

2025-01-01 04:01 UTC, jackstenglein approved these changes

2025-01-01 04:34 UTC, merged

2025-01-01 04:39 UTC, jalpp commented
LETS GET EM 🥳 🔥